name: "Add size label"
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-22.04
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@27a1fdd9e5a5b390573b16072bca0841a1cffce6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
