name: "Add size label"
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-24.04
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@b1f4946f381d38d3b5960f76b514afdfef39b609
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
