name: "Add size label"
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-22.04
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@6ec5bd0f81af1bd8d691180fbf04453b2c4b1642
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
