name: "Add size label"
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-22.04
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@f8edde36b3be04b4f65dcfead05dc8691b374348
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
